#! /bin/sh

set -e

. /usr/share/debconf/confmodule

prevver="$2"

add_system_user() {
    if ! getent passwd <%= project_name %> >/dev/null; then
        adduser --group --system --home /var/lib/<%= project_name %> <%= project_name %>
    fi
}

add_directories() {
    mkdir -p /var/run/<%= project_name %>
    mkdir -p /etc/<%= project_name %>
    mkdir -p /etc/<%= project_name %>/plugin
    mkdir -p /var/log/<%= project_name %>
}

fixperms() {
    dpkg-statoverride --list /var/run/<%= project_name %> >/dev/null || \
        dpkg-statoverride --update --add <%= project_name %> <%= project_name %> 0755 /var/run/<%= project_name %>
    dpkg-statoverride --list /etc/<%= project_name %> >/dev/null || \
        dpkg-statoverride --update --add <%= project_name %> <%= project_name %> 0755 /etc/<%= project_name %>
    dpkg-statoverride --list /var/log/<%= project_name %> >/dev/null || \
        dpkg-statoverride --update --add <%= project_name %> <%= project_name %> 0755 /var/log/<%= project_name %>
}

case "$1" in
    configure)
        add_system_user
        add_directories
        fixperms
        ;;
    abort-upgrade|abort-deconfigure|abort-remove)
        :
        ;;
    *)
        echo "Called with unknown argument $1, bailing out."
        exit 1
        ;;
esac


if [ ! -e "/etc/default/<%= project_name %>" ]; then
  cat > /etc/default/<%= project_name %> <<EOF
# This file is sourced by /bin/sh from /etc/init.d/<%= project_name %>
# Options to pass to <%= project_name %>
TD_AGENT_OPTIONS=""

EOF
fi

<% if install_message %>
if [ "$1" = "configure" ]; then
  echo "<%= install_message %>"
fi
<% end %>

#DEBHELPER#
