# frozen_string_literal: true

require File.expand_path('../config.rb', __FILE__)

source "https://rubygems.org"

# core gems

no_fat_gem = [:ruby]
gem "rake"
gem "bundler", BUNDLER_VERSION
gem "cool.io", "1.7.1",  platforms: no_fat_gem
gem "sigdump", "0.2.4"
gem "http_parser.rb", "0.8.0"
gem "yajl-ruby", "1.4.1"
gem "serverengine", '2.2.4'
gem "msgpack", "1.4.2"
gem "oj", "3.13.9"
gem "tzinfo", "2.0.4"
gem "tzinfo-data", "1.2021.5"
gem "async-http", "0.56.5"
gem "webrick", "1.7.0"

if ENV["INSTALL_GEM_FROM_LOCAL_REPO"]
  # During build process, pre-built fluentd gem will be installed
  # from this local repository, this way is used to avoid embedding full-path
  # into managed Gemfile.lock
  source FLUENTD_LOCAL_GEM_REPO do
    gem "fluentd"
  end
else
  # Lock to specific revision
  git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
  gem "fluentd", github: "fluent/fluentd", ref: FLUENTD_REVISION
end

# plugin gems

gem "elasticsearch", "7.15.0"
gem "fluent-plugin-elasticsearch", "5.1.4"
gem "ruby-kafka", "1.4.0"
gem "digest-murmurhash", "1.1.1"
gem "fluent-plugin-kafka", "0.17.3"
gem "prometheus-client", "2.1.0"
gem "fluent-plugin-prometheus", "2.0.2"
gem "fluent-plugin-prometheus_pushgateway", "0.1.0"
gem "jmespath", "1.4.0"
gem "aws-partitions", "1.534.0"
gem "aws-sdk-core", "3.123.0"
gem "aws-sdk-kms", "1.51.0"
gem "aws-sdk-sqs", "1.47.0"
gem "aws-sigv4", "1.4.0"
gem "aws-sdk-s3", "1.107.0"
gem "fluent-plugin-s3", "1.6.1"
gem "httpclient", "2.8.3"
gem "fluent-diagtool", "1.0.1"
gem "td", "0.16.9"
gem "td-client", "1.0.8"
gem "fluent-plugin-td", "1.1.0"
gem "webhdfs", "0.10.2"
gem "fluent-plugin-webhdfs", "1.5.0"
gem "fluent-plugin-record-modifier", "2.1.0"
gem "fluent-plugin-rewrite-tag-filter", "2.4.0"
gem "nokogiri", "1.13.0"
gem "fluent-plugin-sd-dns", "0.1.0"
gem "fluent-plugin-flowcounter-simple", "0.1.0"
gem "mini_portile2", "2.7.1"
gem "cmetrics", "0.2.5"
gem "fluent-plugin-metrics-cmetrics", "0.1.1"
gem "fluent-plugin-calyptia-monitoring", "0.1.3"

windows_platforms = [:mingw, :x64_mingw] # :mswin
gem "ffi", "1.15.4", platforms: windows_platforms
gem "ffi-win32-extensions", "1.0.4", platforms: windows_platforms
gem "win32-api", "1.10.1", platforms: windows_platforms
gem "win32-event", "0.6.3", platforms: windows_platforms
gem "win32-ipc", "0.7.0", platforms: windows_platforms
gem "win32-service", "2.3.2", platforms: windows_platforms
gem "windows-api", "0.4.4", platforms: windows_platforms
gem "windows-pr", "1.2.6", platforms: windows_platforms
gem "winevt_c", "0.9.3", platforms: windows_platforms
gem "win32-eventlog", "0.6.7", platforms: windows_platforms
gem "fluent-plugin-parser-winevt_xml", "0.2.4", platforms: windows_platforms
gem "fluent-plugin-windows-eventlog", "0.8.1", platforms: windows_platforms

not_windows_platforms = [:ruby]
gem "rdkafka", "0.11.1", platforms: not_windows_platforms
gem "systemd-journal", "1.4.2", platforms: not_windows_platforms
gem "fluent-plugin-systemd", "1.0.5", platforms: not_windows_platforms
gem "fluent-plugin-utmpx", "0.5.0", platforms: not_windows_platforms
