# frozen_string_literal: true

require File.expand_path('../config.rb', __FILE__)

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# core gems

gem "rake"
gem "bundler", "2.2.0.rc1"
gem "cool.io", "1.7.0"
gem "sigdump", "0.2.4"
gem "http_parser.rb", "0.6.0"
gem "yajl-ruby", "1.4.1"
gem "serverengine", '2.2.1'
gem "msgpack", "1.3.3"
gem "oj", "3.10.6"
gem "tzinfo", "2.0.2"
gem "tzinfo-data", "1.2020.1"
gem "async-http", "0.52.4"
gem "fluentd", github: "fluent/fluentd", ref: FLUENTD_REVISION

# https://github.com/socketry/protocol-http2/issues/6
# protocol-http2 0.14.1 causes install error
gem "protocol-http2", "0.14.0"

# plugin gems

gem "elasticsearch", "7.8.1"
gem "fluent-plugin-elasticsearch", "4.1.1"
gem "ruby-kafka", "1.2.0"
gem "fluent-plugin-kafka", "0.14.1"
gem "prometheus-client", "0.9.0"
gem "fluent-plugin-prometheus", "1.8.2"
gem "fluent-plugin-prometheus_pushgateway", "0.0.2"
gem "jmespath", "1.4.0"
gem "aws-partitions", "1.352.0"
gem "aws-sdk-core", "3.104.3"
gem "aws-sdk-kms", "1.36.0"
gem "aws-sdk-sqs", "1.30.0"
gem "aws-sigv4", "1.2.1"
gem "aws-sdk-s3", "1.75.0"
gem "fluent-plugin-s3", "1.4.0"
gem "httpclient", "2.8.2.4"
gem "td", "0.16.9"
gem "td-client", "1.0.7"
gem "fluent-plugin-td", "1.1.0"
gem "webhdfs", "0.9.0"
gem "fluent-plugin-webhdfs", "1.2.5"
gem "fluent-plugin-record-modifier", "2.1.0"
gem "fluent-plugin-rewrite-tag-filter", "2.3.0"
gem "nokogiri", "1.10.10"

windows_platforms = [:mingw, :x64_mingw] # :mswin
gem "ffi", "1.13.1", platforms: windows_platforms
gem "ffi-win32-extensions", "1.0.3", platforms: windows_platforms
gem "win32-api", "1.9.1", platforms: windows_platforms
gem "win32-event", "0.6.3", platforms: windows_platforms
gem "win32-ipc", "0.7.0", platforms: windows_platforms
gem "win32-service", "2.1.5", platforms: windows_platforms
gem "windows-api", "0.4.4", platforms: windows_platforms
gem "windows-pr", "1.2.6", platforms: windows_platforms
gem "winevt_c", "0.8.1", platforms: windows_platforms
gem "win32-eventlog", "0.6.7", platforms: windows_platforms
gem "fluent-plugin-parser-winevt_xml", "0.2.2", platforms: windows_platforms
gem "fluent-plugin-windows-eventlog", "0.7.0", platforms: windows_platforms

not_windows_platforms = [:ruby]
gem "rdkafka", "0.8.0", platforms: not_windows_platforms
gem "systemd-journal", "1.3.3", platforms: not_windows_platforms
gem "fluent-plugin-systemd", "1.0.2", platforms: not_windows_platforms

if ENV["TRAVIS"]
  # Travis CI fails because activesupport requires tzinfo ~> 1.1.
  # We need to wait until activesupport 6.1.
  gem "gh", "0.18.0"
  gem "travis", "1.9.1"
end
