# frozen_string_literal: true

require File.expand_path('../config.rb', __FILE__)

source "https://rubygems.org"

# core gems

no_fat_gem = [:ruby]
gem "rake"
gem "bundler", BUNDLER_VERSION
gem "cool.io", "1.8.0",  platforms: no_fat_gem
gem "sigdump", "0.2.5"
gem "http_parser.rb", "0.8.0"
gem "yajl-ruby", "1.4.3"
gem "serverengine", '2.3.2'
gem "msgpack", "1.7.2"
gem "oj", "3.16.1"
gem "tzinfo", "2.0.6"
gem "tzinfo-data", "1.2023.3"
gem "async", "1.31.0"
gem "async-http", "0.61.0"
gem "webrick", "1.8.1"

# CVE-2023-36617: should be removed after we update Ruby to 3.2.3 or later
gem "uri", "~> 0.12.2"

if ENV["INSTALL_GEM_FROM_LOCAL_REPO"]
  # During build process, pre-built fluentd gem will be installed
  # from this local repository, this way is used to avoid embedding full-path
  # into managed Gemfile.lock
  source FLUENTD_LOCAL_GEM_REPO do
    gem "fluentd"
  end
else
  # Lock to specific revision
  git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
  gem "fluentd", github: "fluent/fluentd", ref: FLUENTD_REVISION
end

# plugin gems

gem "elasticsearch", "8.8.0"
gem "fluent-plugin-elasticsearch", "5.4.0"
gem "ruby-kafka", "1.5.0"
gem "digest-murmurhash", "1.1.1"
gem "fluent-plugin-kafka", "0.19.2"
# f-p-prometheus_pushgateway doesn't support prometheus 3.0 or later
gem "prometheus-client", "2.1.0"
gem "fluent-plugin-prometheus", "2.1.0"
gem "fluent-plugin-prometheus_pushgateway", "0.1.1"
gem "jmespath", "1.6.2"
gem "aws-partitions", "1.785.0"
gem "aws-sdk-core", "3.178.0"
gem "aws-sdk-kms", "1.71.0"
gem "aws-sdk-sqs", "1.61.0"
gem "aws-sigv4", "1.6.0"
gem "aws-sdk-s3", "1.129.0"
gem "fluent-plugin-s3", "1.7.2"
gem "httpclient", "2.8.3"
gem "fluent-diagtool", "1.0.3"
gem "td", "0.17.1"
gem "td-client", "1.0.8"
gem "fluent-plugin-td", "1.2.0"
gem "webhdfs", "0.10.2"
gem "fluent-plugin-webhdfs", "1.5.0"
gem "fluent-plugin-record-modifier", "2.1.1"
gem "fluent-plugin-rewrite-tag-filter", "2.4.0"
gem "fluent-plugin-sd-dns", "0.1.0"
gem "fluent-plugin-flowcounter-simple", "0.1.0"
gem "mini_portile2", "2.8.2"
gem "cmetrics", "0.3.3"
gem "fluent-plugin-metrics-cmetrics", "0.1.2"
gem "fluent-plugin-calyptia-monitoring", "0.1.3"
gem "opensearch-ruby", "2.1.0"
gem "fluent-plugin-opensearch", "1.1.4"

windows_platforms = [:mingw, :x64_mingw] # :mswin
gem "ffi", "1.15.5", platforms: windows_platforms
gem "ffi-win32-extensions", "1.0.4", platforms: windows_platforms
gem "nokogiri", "1.15.5", platforms: windows_platforms
gem "win32-event", "0.6.3", platforms: windows_platforms
gem "win32-ipc", "0.7.0", platforms: windows_platforms
gem "win32-service", "2.3.2", platforms: windows_platforms
gem "winevt_c", "0.10.1", platforms: windows_platforms
gem "win32-eventlog", "0.6.7", platforms: windows_platforms
gem "fluent-plugin-parser-winevt_xml", "0.2.6", platforms: windows_platforms
gem "fluent-plugin-windows-eventlog", "0.8.3", platforms: windows_platforms
gem "fluent-plugin-windows-exporter", "1.0.0", platforms: windows_platforms

not_windows_platforms = [:ruby]
gem "rdkafka", "0.12.0", platforms: not_windows_platforms
gem "systemd-journal", "1.4.2", platforms: not_windows_platforms
gem "fluent-plugin-systemd", "1.0.5", platforms: not_windows_platforms
gem "fluent-plugin-utmpx", "0.5.0", platforms: not_windows_platforms
