#! /bin/sh

set -e

. /usr/share/debconf/confmodule

prevver="$2"

add_system_user() {
    if ! getent passwd _<%= service_name %> >/dev/null; then
	if ! getent passwd <%= compat_service_name %> >/dev/null; then
	    # With underscore prefix, need to disable NAME_REGEX restriction
	    adduser --group --system --force-badname --home /var/lib/<%= package_dir %> _<%= service_name %>
	else
	    if getent group <%= compat_service_name %> >/dev/null; then
		groupmod --new-name _<%= service_name %> <%= compat_service_name %>
	    fi
	    if getent passwd <%= compat_service_name %> >/dev/null; then
		usermod --login _<%= service_name %> <%= compat_service_name %>
	    fi
	fi
    fi
}

add_directories() {
    mkdir -p /var/run/<%= package_dir %>
    mkdir -p /etc/<%= compat_package_dir %>
    mkdir -p /etc/<%= compat_package_dir %>/plugin
    mkdir -p /var/log/<%= compat_package_dir %>
}

fixperms() {
    # If statoverride entry exits, use --force-all to ensure statoverride-add will work.
    # If statoverride entry doen't exit, no need to --force-all.
    dpkg-statoverride --list /var/run/<%= package_dir %> >/dev/null || \
        dpkg-statoverride --update --add _<%= service_name %> _<%= service_name %> 0755 /var/run/<%= package_dir %>
    dpkg-statoverride --list /var/run/<%= package_dir %> >/dev/null && \
        dpkg-statoverride --force-all --update --add _<%= service_name %> _<%= service_name %> 0755 /var/run/<%= package_dir %>
    dpkg-statoverride --list /etc/<%= compat_package_dir %> >/dev/null || \
        dpkg-statoverride --update --add _<%= service_name %> _<%= service_name %> 0755 /etc/<%= compat_package_dir %>
    dpkg-statoverride --list /etc/<%= compat_package_dir %> >/dev/null && \
        dpkg-statoverride --force-all --update --add _<%= service_name %> _<%= service_name %> 0755 /etc/<%= compat_package_dir %>
    dpkg-statoverride --list /var/log/<%= compat_package_dir %> >/dev/null || \
        dpkg-statoverride --update --add _<%= service_name %> _<%= service_name %> 0755 /var/log/<%= compat_package_dir %>
    dpkg-statoverride --list /var/log/<%= compat_package_dir %> >/dev/null && \
        dpkg-statoverride --force-all --update --add _<%= service_name %> _<%= service_name %> 0755 /var/log/<%= compat_package_dir %>
    # Cleanup /var/run/<%= compat_package_dir %>
    dpkg-statoverride --force-all --remove /var/run/<%= compat_package_dir %>
}

case "$1" in
    configure)
        add_system_user
        add_directories
        fixperms
        ;;
    abort-upgrade|abort-deconfigure|abort-remove)
        :
        ;;
    *)
        echo "Called with unknown argument $1, bailing out."
        exit 1
        ;;
esac

<% if install_message %>
if [ "$1" = "configure" ]; then
  echo "<%= install_message %>"
fi
<% end %>

#DEBHELPER#
