#! /bin/sh

set -e

. /usr/share/debconf/confmodule

if [ "$1" = "purge" ]; then
	rm -f /etc/default/<%= compat_service_name %>
	dpkg-statoverride --list /etc/<%= compat_package_dir %> > /dev/null && \
		dpkg-statoverride --remove /etc/<%= compat_package_dir %>
	rm -f /etc/<%= compat_package_dir %>/<%= compat_service_name %>.conf
	rm -rf /etc/<%= compat_package_dir %>
	dpkg-statoverride --list /var/run/<%= package_dir %> > /dev/null && \
		dpkg-statoverride --remove /var/run/<%= package_dir %>
	rm -f /var/run/<%= package_dir %>/*
	rm -rf /var/run/<%= package_dir %>
	dpkg-statoverride --list /var/log/<%= compat_package_dir %> > /dev/null && \
		dpkg-statoverride --remove /var/log/<%= compat_package_dir %>
	rm -rf /var/log/<%= compat_package_dir %>/buffer
	rm -rf /var/log/<%= compat_package_dir %>/*
	rm -rf /var/log/<%= compat_package_dir %>

	getent passwd _<%= service_name %> && userdel -r _<%= service_name %>
fi

#DEBHELPER#
