name: Reusable Build Deb

on:
  workflow_call:
    inputs:
      rake-job:
        required: true
        type: string
      runs-on:
        required: true
        type: string
      next-major:
        required: true
        type: boolean
      cache-group:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: cache rpm
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: cache-rpm
        with:
          path: |
            fluent-package/yum/repositories
            fluent-release/yum/repositories
            fluent-lts-release/yum/repositories
            v7-test/fluent-package/yum/repositories
          key: ${{ runner.os }}-cache-${{ inputs.rake-job }}-${{ runner.arch }}-${{ inputs.cache-group }}-${{ hashFiles('**/config.rb', '**/Rakefile', '**/Gemfile*', '**/*.spec.in', 'fluent-package/templates/**', 'fluent-package/yum/**/Dockerfile') }}
      - uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1.299.0
        with:
          ruby-version: '3.4'
      - name: Install dependencies
        if: ${{ ! steps.cache-rpm.outputs.cache-hit }}
        run: |
          gem install serverspec --no-document
      - name: Build rpm with Docker
        if: ${{ ! steps.cache-rpm.outputs.cache-hit }}
        run: |
          rake yum:build YUM_TARGETS=${{ inputs.rake-job }}
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        if: ${{ ! steps.cache-rpm.outputs.cache-hit && inputs.next-major }}
        with:
          path: v7-test
      - name: Build v7 rpm with Docker
        if: ${{ ! steps.cache-rpm.outputs.cache-hit && inputs.next-major }}
        run: |
          cd v7-test
          git config user.email "fluentd@googlegroups.com"
          git config user.name "Fluentd developers"
          git am fluent-package/bump-version-v7.patch
          rake yum:build YUM_TARGETS=${{ inputs.rake-job }}
      - name: Upload fluent-package rpm
        if: ${{ ! inputs.next-major }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: packages-${{ inputs.rake-job }}
          path: fluent-package/yum/repositories
      - name: Upload fluent-release rpm
        if: ${{ ! inputs.next-major }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: packages-release-${{ inputs.rake-job }}
          path: fluent-release/yum/repositories
      - name: Upload fluent-lts-release rpm
        if: ${{ ! inputs.next-major }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: packages-lts-release-${{ inputs.rake-job }}
          path: fluent-lts-release/yum/repositories
      - name: Upload v7 fluent-package rpm
        if: ${{ inputs.next-major }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: v7-packages-${{ inputs.rake-job }}
          path: v7-test/fluent-package/yum/repositories
