name: Bundle audit
on:
  push:
    branches:
      - master
      - fluent-package-v6
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    name: Audit
    timeout-minutes: 90
    strategy:
      fail-fast: false
    runs-on: windows-2022
    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1.299.0
        with:
          ruby-version: 3.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build
        run: |
          gem install bundle-audit
          cd fluent-package
          bundle-audit check --update
